

fortigates:
      hosts:
        10.233.143.12 

      
      vars:
       ansible_user: jiali60
       ansible_password: Nibuhuidong2@
       vdom: "root"
       ansible_connection: httpapi
       ansible_httpapi_validate_certs: no
       ansible_httpapi_use_ssl: yes
       ansible_network_os: fortinet.fortios.fortios