download_url: https://galaxy.ansible.com/download/fortinet-fortios-2.3.1.tar.gz
format_version: 1.0.0
name: fortios
namespace: fortinet
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.3.1
version_url: https://galaxy.ansible.com/api/v2/collections/fortinet/fortios/versions/2.3.1/
